
version: '3.8'

services:
  thales_db:
    image: postgres:15-alpine
    container_name: thales_db
    restart: always
    environment:
      POSTGRES_DB: thales_system
      POSTGRES_USER: thales_admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - thales_data:/var/lib/postgresql/data
      - ./backend/init_sql.txt:/docker-entrypoint-initdb.d/init.sql
    networks:
      - inercia_net

  thales_api:
    build:
      context: .
      dockerfile: infrastructure/Dockerfile.node.txt
    container_name: thales_api
    restart: always
    depends_on:
      - thales_db
    environment:
      DATABASE_URL: postgres://thales_admin:${DB_PASSWORD}@thales_db:5432/thales_system
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
      PORT: 4000
    networks:
      - inercia_net

  thales_studio:
    build:
      context: .
      dockerfile: infrastructure/Dockerfile.react.txt
    container_name: thales_studio
    restart: always
    ports:
      - "80:80"
    depends_on:
      - thales_api
    networks:
      - inercia_net

networks:
  inercia_net:
    driver: bridge

volumes:
  thales_data:
